sudo: false
language: node_js
node_js:
  - "4.8.0"

before_install:
  - curl https://install.meteor.com/?release=1.4.3.2 | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"

script:
  - (cd tests && meteor npm install)
  - npm run lint
  - npm test
