sudo: false
language: node_js
node_js:
  - "4.4.7"

before_install:
  - curl https://install.meteor.com/?release=1.4.2.3 | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"

script:
  - (cd tests && meteor npm install)
  - npm test
